trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.yml'

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x' # Adjust based on your .NET version

stages:
- stage: Build
  displayName: 'Build & Publish'
  jobs:
  - job: Build_MAUI
    displayName: 'Build MAUI App'
    pool:
      vmImage: 'windows-latest' # Required for MAUI builds
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        version: $(dotNetVersion)
        includePreview: true # Needed for latest MAUI support

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - script: dotnet workload install maui
      displayName: 'Install MAUI Workload'

    - script: dotnet restore
      displayName: 'Restore NuGet Packages'

    # Build Android
    - script: dotnet build YourMauiApp.csproj -c $(buildConfiguration) -f net8.0-android -p:AndroidSigningKeyPass=yourpass -p:AndroidKeyStore=true
      displayName: 'Build Android'

    # Build iOS (requires macOS agent)
    - job: Build_iOS
      displayName: 'Build iOS'
      pool:
        vmImage: 'macOS-latest' # iOS builds require macOS
      steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          version: $(dotNetVersion)
          includePreview: true

      - script: dotnet workload install maui
        displayName: 'Install MAUI Workload'

      - script: dotnet build YourMauiApp.csproj -c $(buildConfiguration) -f net8.0-ios -p:BuildIpa=true
        displayName: 'Build iOS IPA'

    # Build & Publish Web (Blazor Hybrid)
    - script: dotnet publish YourMauiApp.csproj -c $(buildConfiguration) -f net8.0 -o $(Build.ArtifactStagingDirectory)/web
      displayName: 'Publish Blazor Web'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Optional: Add deployment stages for App Center/TestFlight/Play Store