name: Build PROD
on:
  workflow_dispatch:
jobs:
  build:
    name: "Build"
    runs-on: windows-latest
    environment: PROD
    env:
      PROJECT_FILE: "BlazoredLocation/BlazoredLocation/BlazoredLocation/BlazoredLocation.csproj"
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    # - name: Verify solution Path
    #   run: ls -la $SLN_FILE
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PROJECT_FILE --no-restore --configuration Release